### ISSUE TITLE
Example 05-10 does not align properly in Chrome / Edge browsers Version 107.0.5304.107

### ISSUE THREAD

**Issue by idseefeld** [benfrain/rwd4#2]
`<figcaption ...>`s are not aligned like they are in Firefox.
I am referring to example 05-10

Screenshot

![image](https://user-images.githubusercontent.com/866917/203360454-1390bc98-cb7a-4794-803e-f0bf8470cbd2.png)

Kind regards
Dirk

**Comment by benfrain** [comment]
@idseefeld that’s because Chrome/Edge haven’t shipped subgrid yet. There’s a note to check support at the top of page 162. Hopefully they won’t be too long 🤞

**Comment by idseefeld** [comment]
Sorry, should have respected the note.
Great book nevertheless!

**Comment by benfrain** [comment]
> Sorry, should have respected the note.
> Great book nevertheless!

No problem at all 👍 glad it’s proving useful.
